CREATE TABLE Pais (
	Id INT IDENTITY,
	Nome VARCHAR(60) NOT NULL,
	Sigla CHAR(2) NOT NULL,

	CONSTRAINT PK_IdPais PRIMARY KEY (Id),
);

CREATE TABLE Agencia (
	Id INT IDENTITY,
	RazaoSocial VARCHAR(200) NOT NULL,
	CNPJ CHAR(14) NOT NULL,
	Telefone VARCHAR(15) NOT NULL,
	Email VARCHAR(255) NOT NULL,
	Logradouro VARCHAR(200) NOT NULL,
	Numero VARCHAR(10) NOT NULL,
	Bairro VARCHAR(50) NOT NULL,
	Cidade VARCHAR(50) NOT NULL,
	UF CHAR(2) NOT NULL,

	CONSTRAINT PK_IdAgencia PRIMARY KEY (Id)
);

CREATE TABLE Cliente (
	Id INT IDENTITY,
	Nome VARCHAR(60) NOT NULL,
	CPF CHAR(11) NOT NULL,
	Telefone VARCHAR(15) NOT NULL,
	Email VARCHAR(255) NOT NULL,

	CONSTRAINT PK_IdCliente PRIMARY KEY (Id)
);

CREATE TABLE TipoPagamento (
	Id TINYINT IDENTITY,
	Nome VARCHAR(15) NOT NULL,

	CONSTRAINT PK_IdTipoPagamento PRIMARY KEY (Id)
);

CREATE TABLE StatusPagamento (
	Id TINYINT IDENTITY,
	Nome VARCHAR(80) NOT NULL,

	CONSTRAINT PK_IdStatusPagamento PRIMARY KEY (Id)
);

CREATE TABLE StatuReserva (
	Id TINYINT IDENTITY,
	Nome VARCHAR(80) NOT NULL,

	CONSTRAINT PK_IdStatusReserva PRIMARY KEY (Id)
);

CREATE TABLE Pacote (
	Id INT IDENTITY,
	Nome VARCHAR(50) NOT NULL,
	Duracao TINYINT NOT NULL,
	Preco DECIMAL(10, 2) NOT NULL,

	CONSTRAINT PK_IdPacote PRIMARY KEY (Id),
);

CREATE TABLE Hotel (
	Id INT IDENTITY,
	IdPais INT NOT NULL,
	Nome VARCHAR(100) NOT NULL,
	Estrela TINYINT NOT NULL,
	Logradouro VARCHAR(255) NOT NULL,
	Numero VARCHAR(10) NOT NULL,
	Bairro VARCHAR(30) NOT NULL,
	Cidade VARCHAR(50) NOT NULL,
	UF CHAR(2) NOT NULL,

	CONSTRAINT PK_IdHotel PRIMARY KEY (Id),
	CONSTRAINT FK_IdPais_Hotel FOREIGN KEY (IdPais) REFERENCES Pais (Id)
);

CREATE TABLE HotelPacote (
	Id INT IDENTITY,
	IdHotel INT NOT NULL,
	IdPacote INT NOT NULL,
	QuantidadeDias TINYINT NOT NULL,

	CONSTRAINT PK_IdHotelPacote PRIMARY KEY (Id),
	CONSTRAINT FK_IdHotel_HotelPacote FOREIGN KEY (IdHotel) REFERENCES Hotel (Id),
	CONSTRAINT FK_IdPacote_HotelPacote FOREIGN KEY (IdPacote) REFERENCES Pacote (Id)
);

CREATE TABLE Reserva (
	Id INT IDENTITY,
	IdPacote INT NOT NULL,
	IdAgencia INT NOT NULL,
	IdCliente INT NOT NULL,
	IdStatusReserva TINYINT NOT NULL,
	DataReserva DATETIME NOT NULL,
	Quantidade SMALLINT NOT NULL,
	ValorReserva DECIMAL(10, 2) NOT NULL,

	CONSTRAINT PK_IdReserva PRIMARY KEY (Id),
	CONSTRAINT FK_IdPacote_Reserva FOREIGN KEY (IdPacote) REFERENCES Pacote (Id),
	CONSTRAINT FK_IdAgencia_Reserva FOREIGN KEY (IdAgencia) REFERENCES Agencia (Id),
	CONSTRAINT FK_IdCliente_Reserva FOREIGN KEY (IdCliente) REFERENCES Cliente (Id)
);

CREATE TABLE Pagamento (
	Id INT IDENTITY,
	IdReserva INT NOT NULL,
	IdTipoPagamento TINYINT NOT NULL,
	IdStatusPagamento TINYINT NOT NULL,
	DataPagamento DATETIME NOT NULL,
	ValorPago DECIMAL NOT NULL,

	CONSTRAINT PK_IdPagamento PRIMARY KEY (Id),
	CONSTRAINT FK_IdTipoPagamento_Pagamento FOREIGN KEY (IdTipoPagamento) REFERENCES TipoPagamento (Id),
	CONSTRAINT FK_IdStatusPagamento_Pagamento FOREIGN KEY (IdStatusPagamento) REFERENCES StatusPagamento (Id),
);
